services:
  backend:
    image: cabreraevil/nestjs-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    restart: no
    ports:
      - ${PORT-80}:80
    env_file:
      - .env
    networks:
      - template_net
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.2-bookworm
    container_name: template_postgres
    restart: no
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - template_postgres:/var/lib/postgresql/data
    networks:
      - template_net

  redis:
    image: redis/redis-stack-server:7.4.0-rc2-x86_64
    container_name: template_redis
    restart: no
    environment:
      - REDIS_ARGS="--requirepass ${REDIS_PASSWORD}"
    volumes:
      - template_redis:/data
    networks:
      - template_net

networks:
  template_net:
    driver: bridge
    name: template_net

volumes:
  template_redis:
    driver: local
  template_postgres:
    driver: local
