services:
  backend:
    image: cabreraevil/auto-destructive-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-destructive-api
    restart: no
    ports:
      - ${PORT-80}:80
    env_file:
      - .env

