apiVersion: v1
kind: Service
metadata:
  name: auto-destructive-api
  labels:
    helm.sh/chart: deploy-chart-0.1.0
    app.kubernetes.io/name: deploy-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: deploy-chart
    app.kubernetes.io/instance: release-name