apiVersion: v1
kind: Pod
metadata:
  name: 'auto-destructive-api-test-connection'
  labels:
    helm.sh/chart: deploy-chart-0.1.0
    app.kubernetes.io/name: deploy-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: '0.0.1'
    app.kubernetes.io/managed-by: Helm
  annotations:
    'helm.sh/hook': test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['auto-destructive-api:80']
  restartPolicy: Never
