name: Deploy to Kubernetes
description: |
  This workflow deploys the application to a Kubernetes cluster using Helm.
  It runs on pushes to the master and develop branches, and on pull requests to the master branch.
  It sets up the environment, analyzes code, publishes the Docker image, deploys to Kubernetes, and notifies the status.

on:
  push:
    branches:
      - master
      - develop

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  analyze_code:
    name: Analyze
    uses: cabrera-evil/workflows/.github/workflows/code-analysis.yaml@master
    with:
      default_branch: ${{ github.event.repository.default_branch }}
      push_before_sha: ${{ github.event.before }}
      push_base_sha: ${{ github.event.base_ref }}
    secrets: inherit

  analyze_deps:
    name: Analyze
    uses: cabrera-evil/workflows/.github/workflows/deps-analysis.yaml@master
    with:
      report: true
    secrets: inherit

  publish:
    name: Publish
    needs: [analyze_code, analyze_deps]
    uses: cabrera-evil/workflows/.github/workflows/publish-docker.yaml@master
    with:
      docker_image: ${{ github.event.repository.name }}
    secrets: inherit

